micronaut:
  application:
    name: reservation-service

  r2dbc:
    datasources:
      default:
        url: r2dbc:postgresql://${POSTGRES_SERVER:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:reservations}
        username: ${POSTGRES_USER:admin}
        password: ${POSTGRES_PASSWORD:admin123}
        driver: postgres
        max-size: 10

  rabbitmq:
    uri: amqp://${RABBITMQ_USER:guest}:${RABBITMQ_PASSWORD:guest}@${RABBITMQ_SERVER:localhost}:${RABBITMQ_PORT:5672}

  server:
    port: 8083
    rx:
      enabled: true

  logging:
    level:
      io.micronaut: DEBUG
      org.springframework: INFO
